name: word_tab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
          style: italic
    - family: SBL_Greek
      fonts:
        - asset: assets/fonts/SBL_grk.ttf
    - family: SBL_Hebrew
      fonts:
        - asset: assets/fonts/SBL_Hbrw.ttf
    - family: Noto_Sans
      fonts: 
        - asset: assets/fonts/Noto_Sans/NotoSans-Regular.ttf
    - family: Noto_Serif
      fonts: 
       - asset: assets/fonts/Noto_Serif/NotoSerif-Regular.ttf
    - family: Noto_Serif_Hebrew
      fonts: 
        - asset: assets/fonts/Noto_Serif_Hebrew/NotoSerifHebrew-VariableFont.ttf
    